fix: Auth backend which doesn't fully support custom user model
avallbona/Impostor pull request #32
Opened 2021-05-01 04:48 UTC by iamsauravsharma

Fix multiple issue with auth backend. It now supports custom default user manager, support custom username field with help of get_by_natural_field and doesn't use both email and username for getting user if it is not intended choice for custom UserModel instead use get_by_natural_key and at last protect from timing attack as mentioned at https://code.djangoproject.com/ticket/20760

2021-05-03 07:14 UTC, iamsauravsharma commented
Since email login test was failing. I have removed that test. After this fix PR test is not valid test since get_by_natural_key only support username by for default user model. So this PR may be breaking change for package?

2021-05-27 20:45 UTC, avallbona requested changes
Hello @iamsauravsharma, thanks for your contribution. 

I've left some comments. Also, whats do you think about  creating some tests with a customized UserModel? And may be also with a customized USERNAME_FIELD?

Finally, as you commented, this would be a next major versions because it would not be backward compatible.

2021-05-27 20:45 UTC, avallbona commented on impostor/backend.py
> +UserModel = get_user_model()
```suggestion
User = get_user_model()
```

2021-05-27 20:45 UTC, avallbona commented on impostor/backend.py
> +            username = kwargs.get(UserModel.USERNAME_FIELD)
```suggestion
            username = kwargs.get(User.USERNAME_FIELD)
```

2021-05-27 20:45 UTC, avallbona commented on impostor/backend.py
> +                adm_obj = UserModel._default_manager.get_by_natural_key(admin)
```suggestion
                adm_obj = User._default_manager.get_by_natural_key(admin)
```

2021-05-27 20:45 UTC, avallbona commented on impostor/backend.py
> +            except UserModel.DoesNotExist:
```suggestion
            except User.DoesNotExist:
```

2021-05-27 20:45 UTC, avallbona commented on impostor/backend.py
> +            return UserModel._default_manager.get(pk=user_id)
```suggestion
            return User._default_manager.get(pk=user_id)
```

2021-05-27 20:45 UTC, avallbona commented on impostor/backend.py
> +        except UserModel.DoesNotExist:
```suggestion
        except User.DoesNotExist:
```

2021-05-27 20:45 UTC, avallbona commented on impostor/backend.py
> +                auth_user = UserModel._default_manager.get_by_natural_key(uuser)
```suggestion
                auth_user = User._default_manager.get_by_natural_key(uuser)
```

2021-05-27 20:45 UTC, avallbona commented on impostor/backend.py
> +                UserModel().set_password(password)
```suggestion
                User().set_password(password)
```

2021-05-28 12:36 UTC, iamsauravsharma commented
@avallbona I have updated PR with your suggestion. As well as added some test and logs for new authentication fail cases.

2021-05-28 13:29 UTC, iamsauravsharma commented
@avallbona I have updated PR again since earlier update had issue with exception not catched and logged

2021-08-23 14:02 UTC, iamsauravsharma commented
@avallbona Can you review latest changes? This PR is stale for nearly 3 months after last review with no progress

2021-08-24 06:56 UTC, avallbona commented
> @avallbona Can you review latest changes? This PR is stale for nearly 3 months after last review with no progress

I'll do it this weekend

2021-10-03 10:41 UTC, avallbona commented
> @avallbona Can you review latest changes? This PR is stale for nearly 3 months after last review with no progress

LGTM, will merge it very soon and add a few more tests. Thanks.

2022-04-16 15:37 UTC, merged